### ISSUE TITLE
Version 22+ breaks usage of module inside Azure DevOps pipeline when docker container with SQL server is used for integration testing

### ISSUE THREAD

**Issue by crega** [microsoft/SQLServerPSModule#36]
We are experiencing issues regarding connecting to db in v 22+.

We have Azure devOps pipeline that creates docker container with MsSQL server version 2019 as a pipeline resource. We then connect to server and try to create integration tests database. With version 22+ we have issue that pre-handshake failed.

Our Azure pipeline snippet : 
![image](https://user-images.githubusercontent.com/15244223/229767480-48d503e3-5158-4e5b-a4b9-de9c8ee49313.png)

Error that we get when running pipeline:
`A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)`

![image](https://user-images.githubusercontent.com/15244223/229768093-6552940c-8540-43bf-96b3-5f29f6a906e7.png)

Current workaround is **not** to use v 22+. So we had to request `-RequiredVersion 21.1.18256` version in order for our pipeline to work as before.

**Comment by Matteo-T** [comment]
Hi @crega, 

This is the expected breaking change as per roadmap to [secure-by-default](https://github.com/microsoft/SQLServerPSModule/wiki/Secure-by-default:-breaking-changes-going-from-v21-to-v22).

The simple workaround in your case (since you trust your server certificate) would be to use `-TrustServerCertificate` at line 58 of your script.
