### ISSUE TITLE
SQLRegistration does not work with SSMS 20.0 and SqlServer module 22.2.0

### ISSUE THREAD

**Issue by PeterPorsche** [microsoft/SQLServerPSModule#77]
I can add a new item to the "PS SQLSERVER:\SQLRegistration\Database Engine Server Group" but the new item does not show up in SSMS 20.0 "Registerd Servers"

example:
New-Item -Name $(encode-sqlname 'test_reg_server') -ItemType Registration -Value   ("Server=TestServer; Database=test_database; Integrated Security=true");

**Comment by jeffalope** [comment]
Ran into this issue as well.  I think the issue is that the dll: Microsoft.SqlServer.Management.RegisteredServers.dll which I think has references specific for ssms 19.

**Comment by Matteo-T** [comment]
Interesting. This could be tricky to fix/address because I cannot think of away (at least today) to differenciate between 19 and 20. I'll check with the SMO owner and see what we can do about it.

Or maybe I can look at trying to update both (from the PS Provider): whichever is there, I update it. Uhm... I need to take a closer look at the code and see...

**Comment by Matteo-T** [comment]
I've bumped the upcoming version **v22.3** to the latest SMO, so once it's released it should switch to the new SSMS 20 stuff. I cannot think of a simple way to support both at the same time and, hopefully, the bump 19->20 was a fairly isolated case.

**Comment by Matteo-T** [comment]
Can you try v22.3.0 and confirm that the SSMS20 servers are OK now? I can't have both 19 and 20...

**Comment by PeterPorsche** [comment]
Thank you. I confirm that SqlServer module V22.3.0 is working with SSMS20.1, but as you mentioned not with SSMS19.3.
